"""empty message

Revision ID: 105114425523
Revises: a51e189829bb
Create Date: 2023-03-24 08:50:28.479397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '105114425523'
down_revision = 'a51e189829bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_list', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
